########################################################################
# Copyright (c) 1988-2015 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/17/2015
#
# Generic Gcc Makefile for coral cgicatcher Executable
########################################################################

#
# Executable C++ .cpp sources
#
cgicatcher_EXE_CPP_SOURCES += \
${CORAL_SRC}/coral/inet/cgi/environment/variables/writer.cpp \
${CORAL_SRC}/coral/inet/cgi/environment/variables/values.cpp \
${CORAL_SRC}/coral/inet/cgi/environment/variable/value.cpp \
${CORAL_SRC}/coral/inet/cgi/environment/variable/name.cpp \
${CORAL_SRC}/coral/inet/cgi/environment/variable/which.cpp \

cgicatcher_EXE_CPP_SOURCES += \
${CORAL_SRC}/coral/app/cgi/catcher/main.cpp \
${CORAL_SRC}/coral/console/main_main.cpp \

