########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/15/2018
#
# generic Gcc Makefile for coral Executable hellocgi
########################################################################


#
# target
#
hellocgi_EXETARGET = hellocgi

########################################################################

#
# user c++ flags
#
hellocgi_USRCXXFLAGS += \
${coral_USRCXXFLAGS} \

#
# user defines
#
hellocgi_USRDEFINES += \
${coral_USRDEFINES} \

#
# user includes
#
hellocgi_USRINCLUDES += \
${coral_USRINCLUDES} \

#
# user libdirs
#
hellocgi_USRLIBDIRS += \
${coral_USRLIBDIRS} \

########################################################################

#
# Executable .c sources
#
#hellocgi_EXE_C_SOURCES += \
#${CORAL_SRC}/coral/base/Base.c \

#
# Executable .cc sources
#
#hellocgi_EXE_CC_SOURCES += \
#${CORAL_SRC}/coral/base/Base.cc \

#
# Executable .cxx sources
#
#hellocgi_EXE_CXX_SOURCES += \
#${CORAL_SRC}/coral/base/Base.cxx \

#
# Executable .cpp sources
#
hellocgi_EXE_CPP_SOURCES += \
${CORAL_SRC}/coral/app/cgi/hello/cgi.cpp \

#
# Executable .m sources
#
#hellocgi_EXE_M_SOURCES += \
#${CORAL_SRC}/coral/base/Base.m \

#
# Executable .mm sources
#
#hellocgi_EXE_MM_SOURCES += \
#${CORAL_SRC}/coral/base/Base.mm \


########################################################################

#
# Executable libraries
#
hellocgi_LIBS += \
${coral_LIBS}



